# Generated by Django 2.2.7 on 2019-11-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('client_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cell_tech', models.CharField(max_length=20)),
                ('cell_manufacturer', models.CharField(max_length=20)),
                ('no_of_cells', models.CharField(max_length=20)),
                ('no_of_cells_in_series', models.CharField(max_length=20)),
                ('no_of_series_strings', models.CharField(max_length=20)),
                ('no_of_diodes', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('superstate_type', models.CharField(max_length=20)),
                ('superstate_manufacturer', models.CharField(max_length=20)),
                ('substrate_type', models.CharField(max_length=20)),
                ('substrate_manufacturer', models.CharField(max_length=20)),
                ('frame_type', models.CharField(max_length=20)),
                ('frame_adhesive', models.CharField(max_length=20)),
                ('encapsulate_type', models.CharField(max_length=20)),
                ('encapsulate_manufacturer', models.CharField(max_length=20)),
                ('junction_box_type', models.CharField(max_length=20)),
                ('junction_box_manufacturer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('published_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('cell_phone', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete='cascade', to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('fl_required', models.CharField(max_length=20)),
                ('fl_frequency', models.CharField(max_length=20)),
                ('standard', models.ForeignKey(on_delete='DO_NOTHING', to='register.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_voltage', models.CharField(max_length=20)),
                ('voc', models.CharField(max_length=20)),
                ('isc', models.CharField(max_length=20)),
                ('vmp', models.CharField(max_length=20)),
                ('imp', models.CharField(max_length=20)),
                ('pmp', models.CharField(max_length=20)),
                ('ff', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete='DO_NOTHING', to='register.Product')),
                ('sequence_id', models.ForeignKey(on_delete='DO_NOTHING', to='register.Sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete='DO_NOTHING', to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=20)),
                ('report_number', models.IntegerField()),
                ('issue_date', models.DateField(auto_now=True)),
                ('location', models.ForeignKey(on_delete='DO_NOTHING', to='register.Location')),
                ('product', models.ForeignKey(on_delete='DO_NOTHING', to='register.Product')),
                ('standard', models.ForeignKey(on_delete='DO_NOTHING', to='register.Standard')),
                ('user', models.ForeignKey(on_delete='DO_NOTHING', to='register.User')),
            ],
        ),
    ]
